CREATE TABLE [ast].[MbrStg2_MbrData_Test] (
    [mbrStg2_MbrDataUrn]            INT           IDENTITY (1, 1) NOT NULL,
    [ClientSubscriberId]            VARCHAR (50)  NULL,
    [ClientKey]                     VARCHAR (50)  NULL,
    [MstrMrnKey]                    NUMERIC (15)  NOT NULL,
    [LoadType]                      VARCHAR (5)   NULL,
    [mbrLastName]                   VARCHAR (100) NULL,
    [mbrFirstName]                  VARCHAR (100) NULL,
    [mbrMiddleName]                 VARCHAR (100) NULL,
    [mbrSSN]                        VARCHAR (15)  NULL,
    [mbrGENDER]                     VARCHAR (5)   NULL,
    [mbrDob]                        DATE          NULL,
    [mbrInsuranceCardIdNum]         VARCHAR (20)  NULL,
    [mbrMEDICAID_NO]                VARCHAR (15)  NULL,
    [mbrMEDICARE_ID]                VARCHAR (15)  NULL,
    [HICN]                          VARCHAR (11)  NULL,
    [MBI]                           VARCHAR (11)  NULL,
    [mbrEthnicity]                  VARCHAR (20)  NULL,
    [mbrRace]                       VARCHAR (20)  NULL,
    [mbrPrimaryLanguage]            VARCHAR (20)  NULL,
    [prvNPI]                        VARCHAR (10)  NULL,
    [prvTIN]                        VARCHAR (10)  NULL,
    [prvAutoAssign]                 VARCHAR (10)  NULL,
    [prvClientEffective]            DATE          NULL,
    [prvClientExpiration]           DATE          NULL,
    [plnProductPlan]                VARCHAR (50)  NULL,
    [plnProductSubPlan]             VARCHAR (50)  NULL,
    [plnProductSubPlanName]         VARCHAR (50)  NULL,
    [plnMbrIsDualCoverage]          VARCHAR (20)  NULL,
    [plnClientPlanEffective]        DATE          NULL,
    [rspLastName]                   VARCHAR (100) NULL,
    [rspFirstName]                  VARCHAR (100) NULL,
    [rspAddress1]                   VARCHAR (100) NULL,
    [rspAddress2]                   VARCHAR (100) NULL,
    [rspCITY]                       VARCHAR (65)  NULL,
    [rspSTATE]                      CHAR (25)     NULL,
    [rspZIP]                        VARCHAR (20)  NULL,
    [rspPhone]                      VARCHAR (30)  NULL,
    [SrcFileName]                   VARCHAR (100) NULL,
    [AdiTableName]                  VARCHAR (100) NULL,
    [AdiKey]                        INT           NULL,
    [stgRowStatus]                  VARCHAR (20)  NOT NULL,
    [LoadDate]                      DATE          NULL,
    [DataDate]                      DATE          NULL,
    [CreateDate]                    DATETIME      NOT NULL,
    [CreateBy]                      VARCHAR (50)  NOT NULL,
    [MbrMemberKey]                  INT           NULL,
    [MbrPlanKey]                    INT           NULL,
    [MbrPcpKey]                     INT           NULL,
    [MbrCsPlanKey]                  INT           NULL,
    [TransformPcpEffectiveDate]     DATE          NULL,
    [TransfromPcpExpirationDate]    DATE          NULL,
    [TransformPlanEffectiveDate]    DATE          NULL,
    [TransfromPlanExpirationDate]   DATE          NULL,
    [TransformCsPlanEffectiveDate]  DATE          NULL,
    [TransfromCsPlanExpirationDate] DATE          NULL,
    [MbrLoadHistoryKey]             INT           NULL,
    [TransformDemoEffectiveDate]    DATE          NULL,
    [TransformDemoExpirationDate]   DATE          NULL,
    [TransformCsPlanNameDate]       VARCHAR (50)  NULL,
    [plnClientPlanEndDate]          DATE          NULL,
    [stgRowAction]                  VARCHAR (10)  NOT NULL,
    [Member_Dual_Eligible_Flag]     VARCHAR (20)  NULL,
    [MbrState]                      CHAR (2)      NOT NULL,
    [MemberStatus]                  VARCHAR (50)  NULL,
    [MemberOriginalEffectiveDate]   DATE          NULL,
    [RiskScore]                     DECIMAL (5)   NULL,
    [OpportunityScore]              DECIMAL (5)   NULL,
    [MbrCity]                       VARCHAR (50)  NULL,
    [SubscriberID_SHCN_BCBS]        VARCHAR (50)  NULL,
    [Indicator834]                  VARCHAR (50)  NULL,
    [MbrDOD]                        DATE          NULL,
    [ProviderChapter]               VARCHAR (50)  NULL
);

