CREATE TABLE [adi].[Steward_BCBS_Membership] (
    [MembershipKey]                           INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                             VARCHAR (100) NULL,
    [CreateDate]                              DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                                VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                        VARCHAR (100) NULL,
    [LastUpdatedBy]                           VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]                         DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                                DATE          NULL,
    [PatientID]                               DECIMAL (18)  NULL,
    [SubscriberID]                            VARCHAR (30)  NULL,
    [RelationshipCode]                        VARCHAR (3)   NULL,
    [MemberPrefix]                            VARCHAR (4)   NULL,
    [MemberFirstName]                         VARCHAR (35)  NULL,
    [MemberMiddleName]                        VARCHAR (35)  NULL,
    [MemberLastName]                          VARCHAR (35)  NULL,
    [MemberNameSuffix]                        VARCHAR (6)   NULL,
    [MemberBirthDate]                         DATE          NULL,
    [MemberGender]                            CHAR (1)      NULL,
    [MemberLast4DigitsSSN]                    CHAR (4)      NULL,
    [MemberHomeAddress1]                      VARCHAR (55)  NULL,
    [MemberHomeAddress2]                      VARCHAR (55)  NULL,
    [MemberCity]                              VARCHAR (28)  NULL,
    [MemberState]                             CHAR (2)      NULL,
    [MemberZip]                               CHAR (9)      NULL,
    [MemberCounty]                            VARCHAR (255) NULL,
    [MemberPrimaryPhone]                      CHAR (10)     NULL,
    [MemberSecondaryPhone]                    CHAR (10)     NULL,
    [MemberAttributedStatus]                  VARCHAR (9)   NULL,
    [MemberEffectiveDate]                     DATE          NULL,
    [MemberTerminateDate]                     DATE          NULL,
    [AttributedPrimaryCareProviderNPI]        CHAR (10)     NULL,
    [AttributedPrimaryCareProviderPrefix]     CHAR (4)      NULL,
    [AttributedPrimaryCareProviderFirstName]  VARCHAR (35)  NULL,
    [AttributedPrimaryCareProviderMiddle]     VARCHAR (35)  NULL,
    [AttributedPrimaryCareProviderLastName]   VARCHAR (35)  NULL,
    [AttributedPrimaryCareProviderNameSuffix] VARCHAR (20)  NULL,
    [AttributedSpecialistNPI]                 CHAR (10)     NULL,
    [AttributedSpecialistPrefix]              CHAR (4)      NULL,
    [AttributedSpecialistFirstName]           VARCHAR (35)  NULL,
    [AttributedSpecialistMiddle]              VARCHAR (35)  NULL,
    [AttributedSpecialistLastName]            VARCHAR (35)  NULL,
    [AttributedSpecialistNameSuffix]          VARCHAR (29)  NULL,
    [Status]                                  CHAR (1)      CONSTRAINT [dt_bcbsStatus] DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([MembershipKey] ASC)
);

