CREATE TABLE [adi].[Steward_BCBS_MemberCrosswalk] (
    [MemberCrosswalkKey]          INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                 VARCHAR (100) NULL,
    [CreateDate]                  DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                    VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]            VARCHAR (100) NULL,
    [LastUpdatedBy]               VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]             DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                    DATE          NULL,
    [PatientID]                   DECIMAL (18)  NULL,
    [SubscriberID]                VARCHAR (30)  NULL,
    [MemberFirstName]             VARCHAR (35)  NULL,
    [MemberMiddle]                VARCHAR (35)  NULL,
    [MemberLastName]              VARCHAR (35)  NULL,
    [MemberDateBirth]             DATE          NULL,
    [MemberGender]                CHAR (1)      NULL,
    [MemberGenderDescription]     VARCHAR (8)   NULL,
    [MemberLast4SSNdigits]        CHAR (4)      NULL,
    [ExtractID]                   CHAR (14)     NULL,
    [MemberOriginalEffectiveDate] DATE          NULL,
    [Indicator834]                CHAR (1)      NULL,
    [RiskScore]                   DECIMAL (5)   NULL,
    [OpportunityScore]            DECIMAL (5)   NULL,
    [HealthStatus]                VARCHAR (20)  NULL,
    [AssignmentIndicator]         CHAR (3)      NULL,
    [ProgramIndicator]            CHAR (10)     NULL,
    [PriorPatientID]              VARCHAR (18)  NULL,
    [Status]                      CHAR (1)      CONSTRAINT [df_StatusMbrCrwk] DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([MemberCrosswalkKey] ASC)
);

