CREATE TABLE [adi].[Steward_BCBS_MONTHLY_GAPS_IN_CAREDETAIL] (
    [MONTHLYGAPSINCAREDETAILKey] INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                VARCHAR (100) NULL,
    [CreateDate]                 DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                   VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]           VARCHAR (100) NULL,
    [LastUpdatedBy]              VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]            DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                   DATE          NULL,
    [MeasureName]                VARCHAR (100) NULL,
    [IncludedInNumerator]        VARCHAR (10)  NULL,
    [Exclusion]                  VARCHAR (100) NULL,
    [DateTest]                   DATE          NULL,
    [Lab_Test]                   VARCHAR (100) NULL,
    [Test_Result]                VARCHAR (100) NULL,
    [SubscriberID]               VARCHAR (50)  NULL,
    [PatientID]                  VARCHAR (50)  NULL,
    [MemberLastName]             VARCHAR (50)  NULL,
    [MemberFirstName]            VARCHAR (50)  NULL,
    [MemberDOB]                  DATE          NULL,
    [MemberGender]               VARCHAR (10)  NULL,
    [CurrentAttributed_PCP_NPI]  VARCHAR (20)  NULL,
    [CurrentPCPLastName]         VARCHAR (50)  NULL,
    [CurrentPCPFirstName]        VARCHAR (50)  NULL,
    [ProgramIndicator]           VARCHAR (10)  NULL,
    [Status]                     CHAR (1)      DEFAULT ((0)) NULL,
    PRIMARY KEY CLUSTERED ([MONTHLYGAPSINCAREDETAILKey] ASC)
);

