CREATE TABLE [adi].[Steward_BCBS_RXClaim] (
    [RXClaimKey]               INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]              VARCHAR (100) NULL,
    [CreateDate]               DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                 VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]         VARCHAR (100) NULL,
    [LastUpdatedBy]            VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]          DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                 DATE          NULL,
    [ExtractID]                VARCHAR (14)  NULL,
    [ClaimStatusCode]          VARCHAR (2)   NULL,
    [ProviderNPI]              VARCHAR (10)  NULL,
    [ServiceDATE]              DATE          NULL,
    [PatientID]                DECIMAL (18)  NULL,
    [MemberBirthDATE]          DATE          NULL,
    [MemberGender]             CHAR (1)      NULL,
    [MemberFirstName]          VARCHAR (35)  NULL,
    [MemberLastName]           VARCHAR (35)  NULL,
    [MemberHomeAddress1]       VARCHAR (55)  NULL,
    [MemberCityName]           VARCHAR (28)  NULL,
    [MemberStateCode]          VARCHAR (2)   NULL,
    [MemberZipCode]            VARCHAR (5)   NULL,
    [MemberPrimaryPhone]       VARCHAR (10)  NULL,
    [SubscriberID]             VARCHAR (12)  NULL,
    [ClaimID]                  VARCHAR (30)  NULL,
    [NDCCode]                  VARCHAR (14)  NULL,
    [RxID]                     VARCHAR (15)  NULL,
    [FillDate]                 DATE          NULL,
    [NumberofServiceS]         VARCHAR (5)   NULL,
    [NumberofScriptsDispensed] VARCHAR (2)   NULL,
    [DaysSupply]               VARCHAR (4)   NULL,
    [PaidDate]                 DATE          NULL,
    [BrandGenericIndicator]    CHAR (1)      NULL,
    [AdjustmentSequenceNumber] VARCHAR (4)   NULL,
    [ClaimLineNumber]          CHAR (4)      NULL,
    [TherapeuticClassCode]     CHAR (2)      NULL,
    [ProviderLastName]         VARCHAR (35)  NULL,
    [ProviderPhoneNumber]      VARCHAR (10)  NULL,
    [ProviderTIN]              VARCHAR (9)   NULL,
    [PracticeName]             VARCHAR (30)  NULL,
    [ProviderFirstName]        VARCHAR (30)  NULL,
    [ProviderStreetAddress1]   VARCHAR (30)  NULL,
    [ProviderCity]             VARCHAR (15)  NULL,
    [ProviderState]            CHAR (2)      NULL,
    [ProviderZipCode]          CHAR (5)      NULL,
    [DrugFormulation]          CHAR (2)      NULL,
    [AWPAmount]                VARCHAR (9)   NULL,
    [Status]                   CHAR (1)      NULL,
    [ClmsEomLoadStatus]        TINYINT       DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([RXClaimKey] ASC)
);

