CREATE TABLE [adi].[Steward_BCBS_DailyAuth] (
    [DailyAuthKey]                          INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                           VARCHAR (100) NULL,
    [CreateDate]                            DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                              VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                      VARCHAR (100) NULL,
    [LastUpdatedBy]                         VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]                       DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                              DATE          NULL,
    [ICDVersionCode]                        CHAR (2)      NULL,
    [PatientID]                             DECIMAL (18)  NULL,
    [SubscriberID]                          VARCHAR (30)  NULL,
    [MemberGender]                          CHAR (1)      NULL,
    [MemberGenderDescription]               VARCHAR (25)  NULL,
    [MemberBirthDate]                       DATE          NULL,
    [MemberFirstName]                       VARCHAR (35)  NULL,
    [MemberLastName]                        VARCHAR (35)  NULL,
    [MemberZip]                             CHAR (5)      NULL,
    [MemberZipCode_4]                       CHAR (4)      NULL,
    [ProviderTypeDescription]               CHAR (10)     NULL,
    [FacilityName]                          VARCHAR (75)  NULL,
    [ProviderNPI]                           CHAR (10)     NULL,
    [ProviderSpecialtyDescription]          VARCHAR (35)  NULL,
    [ProviderPhoneNumber]                   CHAR (10)     NULL,
    [ProviderStreetAddress1]                VARCHAR (35)  NULL,
    [ProviderStreetAddress2]                VARCHAR (35)  NULL,
    [ProviderCity]                          VARCHAR (28)  NULL,
    [ProviderState]                         CHAR (2)      NULL,
    [ProviderZipCode]                       CHAR (5)      NULL,
    [AttendingProviderTypeDescription]      VARCHAR (35)  NULL,
    [AttendingProviderID_NPI]               CHAR (10)     NULL,
    [AttendingProviderSpecialtyDescription] VARCHAR (35)  NULL,
    [AttendingProviderPhoneNumber]          CHAR (10)     NULL,
    [AttendingProviderFirstName]            VARCHAR (35)  NULL,
    [AttendingProviderLastName]             VARCHAR (35)  NULL,
    [AttendingProviderStreetAddress1]       VARCHAR (55)  NULL,
    [AttendingProviderStreetAddress2]       VARCHAR (35)  NULL,
    [AttendingProviderCity]                 VARCHAR (28)  NULL,
    [AttendingProviderState]                CHAR (2)      NULL,
    [AttendingProviderZipCode]              CHAR (5)      NULL,
    [AuthorizationNumber]                   VARCHAR (30)  NULL,
    [NotificationDate]                      DATE          NULL,
    [AdmissionDate]                         DATE          NULL,
    [DischargeDate]                         DATE          NULL,
    [RequestedAdmissionDate]                DATE          NULL,
    [RequestedDischargeDate]                DATE          NULL,
    [TypeServiceCode]                       CHAR (5)      NULL,
    [TypeServiceDescription]                VARCHAR (100) NULL,
    [TreatmentSettingCode]                  VARCHAR (10)  NULL,
    [TreatmentSettingDescription]           VARCHAR (100) NULL,
    [DiagnosisCode]                         CHAR (10)     NULL,
    [DiagnosisCodeDescription]              VARCHAR (200) NULL,
    [PrimaryDiagnosisFlag]                  CHAR (1)      NULL,
    [PatientDischargeStatusCode]            CHAR (10)     NULL,
    [PatientDischargeCodeDescription]       CHAR (32)     NULL,
    [TreatmentUrgencyDescription]           VARCHAR (100) NULL,
    [ExtractID]                             CHAR (4)      NULL,
    [Status]                                CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([DailyAuthKey] ASC)
);

