CREATE TABLE [adi].[z_Steward_BCBS_BlueCap] (
    [BlueCapKey]                       INT           IDENTITY (1, 1) NOT NULL,
    [SrcFileName]                      VARCHAR (100) NULL,
    [CreateDate]                       DATETIME      DEFAULT (sysdatetime()) NULL,
    [CreateBy]                         VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [OriginalFileName]                 VARCHAR (100) NULL,
    [LastUpdatedBy]                    VARCHAR (100) DEFAULT (suser_sname()) NULL,
    [LastUpdatedDate]                  DATETIME      DEFAULT (sysdatetime()) NULL,
    [DataDate]                         DATE          NULL,
    [MemberNumber]                     VARCHAR (11)  NULL,
    [Filler_11]                        CHAR (1)      NULL,
    [MemberName]                       VARCHAR (30)  NULL,
    [MemberDateBirth]                  DATE          NULL,
    [MemberGender]                     VARCHAR (1)   NULL,
    [MemberBenefitCode]                VARCHAR (10)  NULL,
    [AccountControlNumber]             VARCHAR (10)  NULL,
    [BenefitAgreementControlNumber]    VARCHAR (10)  NULL,
    [ServiceProviderID]                VARCHAR (10)  NULL,
    [CapitationPeriodDate]             DATE          NULL,
    [PaymentCode]                      CHAR (1)      NULL,
    [Filler_4]                         CHAR (4)      NULL,
    [SpecialistCopayAmount]            DECIMAL (7)   NULL,
    [RadiologyCopayAmount]             DECIMAL (7)   NULL,
    [Filler_82]                        CHAR (82)     NULL,
    [NetChargePaymentAmount]           DECIMAL (6)   NULL,
    [Filler_6]                         CHAR (6)      NULL,
    [Filler_7_1]                       CHAR (7)      NULL,
    [Filler_7_2]                       CHAR (7)      NULL,
    [MedicalHomeManagementFee]         DECIMAL (7)   NULL,
    [Filler_7_3]                       CHAR (7)      NULL,
    [Filler_7_4]                       CHAR (7)      NULL,
    [Filler_7_5]                       CHAR (7)      NULL,
    [MedicareStatusIndicator]          VARCHAR (2)   NULL,
    [OfficeVisitCopayAmount]           DECIMAL (7)   NULL,
    [Filler_1_2]                       CHAR (1)      NULL,
    [RetroactivityIndicator]           CHAR (1)      NULL,
    [Filler_31]                        CHAR (31)     NULL,
    [PatientID]                        VARCHAR (18)  NULL,
    [ProgramIndicator]                 VARCHAR (10)  NULL,
    [PaymentDate]                      DATE          NULL,
    [CorporateEntityCode]              VARCHAR (3)   NULL,
    [ProductTypeCode]                  VARCHAR (3)   NULL,
    [AttributedPrimaryCareProviderNPI] CHAR (10)     NULL,
    [Status]                           CHAR (1)      NULL,
    PRIMARY KEY CLUSTERED ([BlueCapKey] ASC)
);

